In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlp

In [ ]:
import io
from google.colab import files
uploaded=files.upload()

Saving studentdetails2.csv to studentdetails2.csv

In [ ]:
datafile=pd.read_csv("studentdetails2.csv")

In [ ]:
datafile.head()

   ROLLNO      NAME       ADDRESS DEPARTMENT
0     1.0     Madhu       Nandyal        CSE
1     2.0    Mahesh     Hyderabad      CIVIL
2     3.0    Prabas    Vijayawada       MECH
3     4.0    Sruthi        Guntur        ECE
4     5.0  Rashmika  Srikakularam        EEE

In [ ]:
datafile.drop

<bound method DataFrame.drop of     ROLLNO         NAME        ADDRESS DEPARTMENT
0      1.0        Madhu        Nandyal        CSE
1      2.0       Mahesh      Hyderabad      CIVIL
2      3.0       Prabas     Vijayawada       MECH
3      4.0       Sruthi         Guntur        ECE
4      5.0     Rashmika   Srikakularam        EEE
5      6.0     Samantha  Vijayanagaram        CSE
6      7.0        Arjun          Vizag      CIVIL
7      8.0        Vijay       Godavari       MECH
8      9.0      Sweetie        Nellore        ECE
9     10.0         Ajay   Ananthapuram        EEE
10    11.0       Suresh         Kadapa        CSE
11    12.0        Madhu        Chitoor      CIVIL
12    13.0        Pavan   Ananthapuram       MECH
13    14.0        Sudha      Hyderabad        ECE
14     NaN  Raghavendra  Vijayanagaram        EEE
15    16.0        Surya          Vizag        CSE
16    17.0        Bommi      Hyderabad      CIVIL
17     NaN         Maha     Vijayawada       MECH
18    19.0        Sneha     Vijayawada        ECE
19    20.0        Sanju         Guntur        EEE>

In [ ]:
datafile.dropna()

    ROLLNO      NAME        ADDRESS DEPARTMENT
0      1.0     Madhu        Nandyal        CSE
1      2.0    Mahesh      Hyderabad      CIVIL
2      3.0    Prabas     Vijayawada       MECH
3      4.0    Sruthi         Guntur        ECE
4      5.0  Rashmika   Srikakularam        EEE
5      6.0  Samantha  Vijayanagaram        CSE
6      7.0     Arjun          Vizag      CIVIL
7      8.0     Vijay       Godavari       MECH
8      9.0   Sweetie        Nellore        ECE
9     10.0      Ajay   Ananthapuram        EEE
10    11.0    Suresh         Kadapa        CSE
11    12.0     Madhu        Chitoor      CIVIL
12    13.0     Pavan   Ananthapuram       MECH
13    14.0     Sudha      Hyderabad        ECE
15    16.0     Surya          Vizag        CSE
16    17.0     Bommi      Hyderabad      CIVIL
18    19.0     Sneha     Vijayawada        ECE
19    20.0     Sanju         Guntur        EEE

In [ ]:
datafile.fillna(0)

    ROLLNO         NAME        ADDRESS DEPARTMENT
0      1.0        Madhu        Nandyal        CSE
1      2.0       Mahesh      Hyderabad      CIVIL
2      3.0       Prabas     Vijayawada       MECH
3      4.0       Sruthi         Guntur        ECE
4      5.0     Rashmika   Srikakularam        EEE
5      6.0     Samantha  Vijayanagaram        CSE
6      7.0        Arjun          Vizag      CIVIL
7      8.0        Vijay       Godavari       MECH
8      9.0      Sweetie        Nellore        ECE
9     10.0         Ajay   Ananthapuram        EEE
10    11.0       Suresh         Kadapa        CSE
11    12.0        Madhu        Chitoor      CIVIL
12    13.0        Pavan   Ananthapuram       MECH
13    14.0        Sudha      Hyderabad        ECE
14     0.0  Raghavendra  Vijayanagaram        EEE
15    16.0        Surya          Vizag        CSE
16    17.0        Bommi      Hyderabad      CIVIL
17     0.0         Maha     Vijayawada       MECH
18    19.0        Sneha     Vijayawada        ECE
19    20.0        Sanju         Guntur        EEE

In [ ]:
datafile.fillna(0)
datafile["ROLLNO"].mean()

9.833333333333334

In [ ]:
datafile.fillna(0)
datafile["ROLLNO"].median()

9.5

In [ ]:
datafile.fillna(0)
datafile["ROLLNO"].mode()

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    16.0
15    17.0
16    19.0
17    20.0
dtype: float64